<template><div><h1 id="docker镜像打包导入到另一台服务器" tabindex="-1"><a class="header-anchor" href="#docker镜像打包导入到另一台服务器" aria-hidden="true">#</a> docker镜像打包导入到另一台服务器</h1>
<p>1.找到要打包的镜像</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>jaegertracing<span class="token operator">/</span><span class="token keyword">all</span><span class="token operator">-</span><span class="token operator">in</span><span class="token operator">-</span>one                   <span class="token number">1.16</span>      fea586ade9d0   <span class="token number">22</span> months ago   <span class="token number">50.5</span>MB
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>2.打包成文件</p>
<div class="language-sql ext-sql line-numbers-mode"><pre v-pre class="language-sql"><code>docker <span class="token keyword">save</span> <span class="token operator">-</span>o cc<span class="token punctuation">.</span>tar jaegertracing<span class="token operator">/</span><span class="token keyword">all</span><span class="token operator">-</span><span class="token operator">in</span><span class="token operator">-</span>one:<span class="token number">1.16</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>3.ls 查看刚才以打包的文件</p>
<div class="language-csharp ext-cs line-numbers-mode"><pre v-pre class="language-csharp"><code><span class="token punctuation">[</span>root@master3 <span class="token operator">~</span><span class="token punctuation">]</span># ls
anaconda<span class="token operator">-</span><span class="token return-type class-name">ks<span class="token punctuation">.</span>cfg</span>  cc<span class="token punctuation">.</span><span class="token function">tar</span><span class="token punctuation">(</span>已打包的<span class="token punctuation">)</span>  kubeadm<span class="token operator">-</span>config<span class="token punctuation">.</span>yaml
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>4.导入到需要镜像的服务器</p>
<div class="language-kotlin ext-kt line-numbers-mode"><pre v-pre class="language-kotlin"><code>scp cc<span class="token punctuation">.</span>tar <span class="token label symbol">root@</span><span class="token number">192.168</span><span class="token punctuation">.</span><span class="token number">200.130</span><span class="token operator">:</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>5.解压镜像文件</p>
<div class="language-yaml ext-yml line-numbers-mode"><pre v-pre class="language-yaml"><code><span class="token punctuation">[</span>root@node1 ~<span class="token punctuation">]</span><span class="token comment"># docker load &lt; cc.tar </span>
<span class="token key atrule">8f1b3d3ad470</span><span class="token punctuation">:</span> Loading layer <span class="token punctuation">[</span>==================================================<span class="token punctuation">></span><span class="token punctuation">]</span>  217.6kB/217.6kB
<span class="token key atrule">44874aec6671</span><span class="token punctuation">:</span> Loading layer <span class="token punctuation">[</span>==================================================<span class="token punctuation">></span><span class="token punctuation">]</span>  45.46MB/45.46MB
<span class="token key atrule">68b1a9835e66</span><span class="token punctuation">:</span> Loading layer <span class="token punctuation">[</span>==================================================<span class="token punctuation">></span><span class="token punctuation">]</span>  3.584kB/3.584kB
<span class="token key atrule">Loaded image</span><span class="token punctuation">:</span> jaegertracing/all<span class="token punctuation">-</span>in<span class="token punctuation">-</span>one<span class="token punctuation">:</span><span class="token number">1.20</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>6.查看刚才导出的镜像</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token punctuation">[</span>root@node1 ~<span class="token punctuation">]</span><span class="token comment"># docker images </span>
REPOSITORY              
registry.aliyuncs.com/google_containers/pause                          <span class="token number">3.2</span>       80d28bedfe5d   <span class="token number">20</span> months ago   683kB
registry.aliyuncs.com/google_containers/coredns                        <span class="token number">1.6</span>.7     67da37a9a360   <span class="token number">21</span> months ago   <span class="token number">43</span>.8MB
jaegertracing/all-in-one             <span class="token comment"># 已解压的镜像                      1.16      fea586ade9d0   22 months ago   50.5MB             </span>
registry.aliyuncs.com/google_containers/etcd                           <span class="token number">3.4</span>.3-0   303ce5db0e90   <span class="token number">2</span> years ago     288MB
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


