<template><div><ul>
<li><a href="http://cubxxw.com" target="_blank" rel="noopener noreferrer">author<ExternalLinkIcon/></a></li>
</ul>
<h1 id="第53节-cloudbuildai" tabindex="-1"><a class="header-anchor" href="#第53节-cloudbuildai" aria-hidden="true">#</a> 第53节 CloudBuildAI</h1>
<div><a href = '52.md' style='float:left'>⬆️上一节🔗  </a><a href = '54.md' style='float: right'>  ⬇️下一节🔗</a></div>
<br>
<blockquote>
<p>❤️💕💕记录<a href="https://github.com/cubxxw/sealos" target="_blank" rel="noopener noreferrer">sealos<ExternalLinkIcon/></a>开源项目的学习过程。<a href="https://github.com/cubxxw/sealos" target="_blank" rel="noopener noreferrer">k8s,docker和云原生的学习<ExternalLinkIcon/></a>。Myblog:<a href="http://cubxxw.com/" target="_blank" rel="noopener noreferrer">http://cubxxw.com<ExternalLinkIcon/></a></p>
</blockquote>
<hr>
<p>[TOC]</p>
<h2 id="project-overview" tabindex="-1"><a class="header-anchor" href="#project-overview" aria-hidden="true">#</a> Project Overview</h2>
<p>CloudBuildAI is an automated cloud-native application building and deployment tool that uses AI technology to generate Dockerfiles, Kubernetes YAML files, and other cloud platform deployment configurations for users.</p>
<p>In cloud-native application development, building Docker images and writing Kubernetes deployment files is a tedious and important task, and that's where CloudBuildAI comes in.</p>
<p>CloudBuildAI can automatically generate Dockerfiles and Kubernetes deployment files by inputting a GitHub repository address and automatically deploy the application on Sealos. If the files generated by AI are not accurate enough, CloudBuildAI can continuously optimize the accuracy of file generation through automatic repair and human feedback.</p>
<h2 id="project-purpose" tabindex="-1"><a class="header-anchor" href="#project-purpose" aria-hidden="true">#</a> Project Purpose</h2>
<ul>
<li>Simplify the cloud-native application deployment process</li>
<li>Make it easy for more developers to achieve automated CI/CD</li>
<li>Generate accurate Dockerfiles and Kubernetes YAML files through AI technology</li>
<li>Continuously optimize and improve, fix incorrect configurations, and improve deployment efficiency</li>
</ul>
<h2 id="quick-start" tabindex="-1"><a class="header-anchor" href="#quick-start" aria-hidden="true">#</a> Quick Start</h2>
<ol>
<li>Submit your GitHub repository address to CloudBuildAI</li>
<li>CloudBuildAI analyzes the code and generates Dockerfile and Kubernetes YAML files</li>
<li>Check the generated files and submit feedback to CloudBuildAI</li>
<li>CloudBuildAI continuously optimizes and improves</li>
<li>Merge the files generated by CloudBuildAI into the repository to achieve automated deployment!</li>
</ol>
<h2 id="project-license" tabindex="-1"><a class="header-anchor" href="#project-license" aria-hidden="true">#</a> Project License</h2>
<p>CloudBuildAI follows the <a href="./LICENSE">MIT open source license</a>.</p>
<p>Welcome to use and improve CloudBuildAI! We are committed to creating a more intelligent and easy-to-use cloud application deployment tool.</p>
<h2 id="contributor-guidelines" tabindex="-1"><a class="header-anchor" href="#contributor-guidelines" aria-hidden="true">#</a> Contributor Guidelines</h2>
<p>See <a href="http://CONTRIBUTING.md" target="_blank" rel="noopener noreferrer">CONTRIBUTING.md<ExternalLinkIcon/></a> for details.</p>
<p>We welcome your contributions! You can participate in the development of CloudBuildAI by submitting bug reports and pull requests.</p>
<blockquote>
<p>👉 <strong>Note:</strong> The CloudBuildAI project is a preview version under development, all documents and codes are for reference only. The CloudBuildAI project may change frequently, and we do not guarantee that the information provided is the latest or accurate.</p>
</blockquote>
<h2 id="end-链接" tabindex="-1"><a class="header-anchor" href="#end-链接" aria-hidden="true">#</a> END 链接</h2>
<ul><li><div><a href = '52.md' style='float:left'>⬆️上一节🔗  </a><a href = '54.md' style='float: right'>  ️下一节🔗</a></div></li></ul>
<ul>
<li>
<p><RouterLink to="/">Ⓜ️回到目录🏠</RouterLink></p>
</li>
<li>
<p><a href="https://cubxxw.com/archives/contributors" target="_blank" rel="noopener noreferrer"><strong>🫵参与贡献💞❤️‍🔥💖</strong><ExternalLinkIcon/></a>)</p>
</li>
<li>
<p>✴️版权声明 © ：本书所有内容遵循<a href="http://zh.wikipedia.org/wiki/Wikipedia:CC-by-sa-3.0%E5%8D%8F%E8%AE%AE%E6%96%87%E6%9C%AC" target="_blank" rel="noopener noreferrer">CC-BY-SA 3.0协议（署名-相同方式共享）©<ExternalLinkIcon/></a></p>
</li>
</ul>
</div></template>


