<template><div><ul>
<li><a href="http://nsddd.top" target="_blank" rel="noopener noreferrer">author<ExternalLinkIcon/></a></li>
</ul>
<h1 id="第63节-readme-模板和设计" tabindex="-1"><a class="header-anchor" href="#第63节-readme-模板和设计" aria-hidden="true">#</a> 第63节 README 模板和设计</h1>
<div><a href = '62.md' style='float:left'>⬆️上一节🔗  </a><a href = '64.md' style='float: right'>  ⬇️下一节🔗</a></div>
<br>
<blockquote>
<p>❤️💕💕记录<a href="https://github.com/cubxxw/sealos" target="_blank" rel="noopener noreferrer">sealos<ExternalLinkIcon/></a>开源项目的学习过程。<a href="https://github.com/cubxxw/sealos" target="_blank" rel="noopener noreferrer">k8s,docker和云原生的学习<ExternalLinkIcon/></a>。Myblog:<a href="http://nsddd.top/" target="_blank" rel="noopener noreferrer">http://nsddd.top<ExternalLinkIcon/></a></p>
</blockquote>
<hr>
<p>[TOC]</p>
<div class="language-markdown ext-md line-numbers-mode"><pre v-pre class="language-markdown"><code>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>h1</span> <span class="token attr-name">align</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>center<span class="token punctuation">"</span></span> <span class="token special-attr"><span class="token attr-name">style</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span><span class="token value css language-css"><span class="token property">border-bottom</span><span class="token punctuation">:</span> none</span><span class="token punctuation">"</span></span></span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>b</span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>{blog}<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>{name}<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>br</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>b</span><span class="token punctuation">></span></span>
    ⭐️  Open source Instant Messaging Server  ⭐️ <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>br</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>h1</span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">align</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span>center</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://goreportcard.com/report/github.com/{github}<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>img</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://goreportcard.com/badge/github.com/{github}<span class="token punctuation">"</span></span> <span class="token attr-name">alt</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>A+<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>&lt;https://github.com/issues?q=org%3A{organization}+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee><span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>img</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>&lt;https://img.shields.io/github/issues/{github}/good%20first%20issue?logo=%22github%22><span class="token punctuation">"</span></span> <span class="token attr-name">alt</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>good first<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://github.com/{github}><span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>img</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>&lt;https://img.shields.io/github/stars/{github}.svg?style=flat&amp;logo=github&amp;colorB=deeppink&amp;label=stars<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>img</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>&lt;https://img.shields.io/badge/Slack-100%2B-blueviolet?logo=slack<span class="token entity named-entity" title="&amp;">&amp;amp;</span>logoColor=white<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://github.com/{github}/blob/main/LICENSE<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>img</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>&lt;https://img.shields.io/badge/license-Apache--2.0-green<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://golang.org/<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>img</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://img.shields.io/badge/Language-Go-blue.svg<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">align</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>center<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>./README.md<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>b</span><span class="token punctuation">></span></span>English<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>b</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span> •
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>./README_zh.md<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>b</span><span class="token punctuation">></span></span>中文<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>b</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="awesome-features" tabindex="-1"><a class="header-anchor" href="#awesome-features" aria-hidden="true">#</a> Awesome features</h2>
<ul>
<li>…</li>
</ul>
<h2 id="quickstart" tabindex="-1"><a class="header-anchor" href="#quickstart" aria-hidden="true">#</a> Quickstart</h2>
<blockquote>
<p><strong>Note</strong>: You can get started quickly with {name}.</p>
</blockquote>
<h2 id="contributing-development" tabindex="-1"><a class="header-anchor" href="#contributing-development" aria-hidden="true">#</a> Contributing &amp; Development</h2>
<p>OpenIM Our goal is to build a top-level open source community. We have a set of standards, in the <a href="https://github.com/OpenIMSDK/community" target="_blank" rel="noopener noreferrer">Community repository<ExternalLinkIcon/></a>.</p>
<p>If you'd like to contribute to this {name} repository, please read our <a href="https://github.com/%7Bgithub%7D/blob/main/CONTRIBUTING.md" target="_blank" rel="noopener noreferrer">contributor documentation<ExternalLinkIcon/></a>.</p>
<h2 id="community-meeting" tabindex="-1"><a class="header-anchor" href="#community-meeting" aria-hidden="true">#</a> community meeting</h2>
<p>We welcome everyone to join us and contribute to {name}, whether you are new to open source or professional. We are committed to promoting an open source culture, so we offer community members neighborhood prizes and reward money in recognition of their contributions. We believe that by working together, we can build a strong community and make valuable open source tools and resources available to more people. So if you are interested in {name}, please join our community and start contributing your ideas and skills!</p>
<p>We take notes of each <a href="https://github.com/OpenIMSDK/Open-IM-Server/issues/381" target="_blank" rel="noopener noreferrer">biweekly meeting<ExternalLinkIcon/></a> in <a href="https://github.com/OpenIMSDK/Open-IM-Server/discussions/categories/meeting" target="_blank" rel="noopener noreferrer">GitHub discussions<ExternalLinkIcon/></a>, and our minutes are written in <a href="https://docs.google.com/document/d/1nx8MDpuG74NASx081JcCpxPgDITNTpIIos0DS6Vr9GU/edit?usp=sharing" target="_blank" rel="noopener noreferrer">Google Docs<ExternalLinkIcon/></a>.</p>
<p>{name} maintains a <a href="https://github.com/OpenIMSDK/community/tree/main/roadmaps" target="_blank" rel="noopener noreferrer">public roadmap<ExternalLinkIcon/></a>. It gives a a high-level view of the main priorities for the project, the maturity of different features and projects, and how to influence the project direction.</p>
<h2 id="about-openim" tabindex="-1"><a class="header-anchor" href="#about-openim" aria-hidden="true">#</a> about OpenIM</h2>
<h3 id="common" tabindex="-1"><a class="header-anchor" href="#common" aria-hidden="true">#</a> common</h3>
<ul>
<li>https://github.com/OpenIMSDK/automation: OpenIM Automation, cicd, and actions, Robotics.</li>
<li>https://github.com/OpenIMSDK/community: Community Management for OpenIM</li>
</ul>
<h3 id="openim-links" tabindex="-1"><a class="header-anchor" href="#openim-links" aria-hidden="true">#</a> OpenIM <strong>Links</strong></h3>
<p>Contains some common parts of the OpenIM community.</p>
<ul>
<li>https://github.com/OpenIMSDK/automation: OpenIM Automation, cicd, and actions, Robotics.</li>
<li>https://github.com/OpenIMSDK/openim-sdk-core: The IMSDK implemented by golang can be used in IOS, Android, PC and other platforms.</li>
<li>https://github.com/OpenIMSDK/Open-IM-Server: Instant messaging IM server.</li>
<li>https://github.com/OpenIMSDK/community: Community Management for OpenIM.</li>
</ul>
<h3 id="sdks" tabindex="-1"><a class="header-anchor" href="#sdks" aria-hidden="true">#</a> SDKs</h3>
<ul>
<li><a href="https://github.com/OpenIMSDK/Open-IM-SDK-Core" target="_blank" rel="noopener noreferrer">Open-IM-SDK-Core<ExternalLinkIcon/></a>: A cross-platform SDK implemented in golang that can be used in IOS, Android, PC, and other platforms.</li>
<li><a href="https://github.com/OpenIMSDK/Open-IM-SDK-iOS" target="_blank" rel="noopener noreferrer">Open-IM-SDK-iOS<ExternalLinkIcon/></a>: An iOS SDK generated based on Open-IM-SDK-Core, available for developers to reference.</li>
<li><a href="https://github.com/OpenIMSDK/Open-IM-SDK-Android" target="_blank" rel="noopener noreferrer">Open-IM-SDK-Android<ExternalLinkIcon/></a>: An Android SDK generated based on Open-IM-SDK-Core, available for developers to reference.</li>
<li><a href="https://github.com/OpenIMSDK/Open-IM-SDK-Flutter" target="_blank" rel="noopener noreferrer">Open-IM-SDK-Flutter<ExternalLinkIcon/></a>: A Flutter SDK generated based on Open-IM-SDK-iOS and Open-IM-SDK-Android, available for developers to reference.</li>
<li><a href="https://github.com/OpenIMSDK/Open-IM-SDK-Uniapp" target="_blank" rel="noopener noreferrer">Open-IM-SDK-Uniapp<ExternalLinkIcon/></a>: A uni-app SDK generated based on Open-IM-SDK-iOS and Open-IM-SDK-Android, available for developers to reference.</li>
</ul>
<h3 id="demos" tabindex="-1"><a class="header-anchor" href="#demos" aria-hidden="true">#</a> Demos</h3>
<ul>
<li><a href="https://github.com/OpenIMSDK/Open-IM-iOS-Demo" target="_blank" rel="noopener noreferrer">Open-IM-iOS-Demo<ExternalLinkIcon/></a>: An iOS demo based on Open-IM-SDK-iOS, available for developers to reference.</li>
<li><a href="https://github.com/OpenIMSDK/Open-IM-Android-Demo" target="_blank" rel="noopener noreferrer">Open-IM-Android-Demo<ExternalLinkIcon/></a>: An Android demo based on Open-IM-SDK-Android, available for developers to reference.</li>
<li><a href="https://github.com/OpenIMSDK/Open-IM-Flutter-Demo" target="_blank" rel="noopener noreferrer">Open-IM-Flutter-Demo<ExternalLinkIcon/></a>: A Flutter demo based on Open-IM-SDK-Flutter, available for developers to reference.</li>
</ul>
<h2 id="used-by" tabindex="-1"><a class="header-anchor" href="#used-by" aria-hidden="true">#</a> Used By</h2>
<p>OpenIM is used by the following companies ,let's write it down in <a href="https://github.com/OpenIMSDK/community/blob/main/ADOPTERS.md" target="_blank" rel="noopener noreferrer">ADOPTER<ExternalLinkIcon/></a>S.</p>
<p>Please leave your use cases in the comments <a href="https://github.com/OpenIMSDK/Open-IM-Server/issues/379" target="_blank" rel="noopener noreferrer">here<ExternalLinkIcon/></a>.</p>
<h2 id="license" tabindex="-1"><a class="header-anchor" href="#license" aria-hidden="true">#</a> License</h2>
<p>Sealer is licensed under the Apache License, Version 2.0. See <a href="https://github.com/OpenIMSDK/%7Bname%7D/LICENSE" target="_blank" rel="noopener noreferrer">LICENSE<ExternalLinkIcon/></a> for the full license text.</p>
<div class="language-markdown ext-md line-numbers-mode"><pre v-pre class="language-markdown"><code><span class="token url">[<span class="token content">![FOSSA Status</span>](<span class="token url">https://app.fossa.com/api/projects/git%2Bgithub.com%2Fsealerio%2Fsealer.svg?type=large</span>)</span>](https://app.fossa.com/projects/git%2Bgithub.com%2FOpenIMSDK%2FOpen-IM-SDK-Core?ref=badge_large)
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="thanks-to-our-contributors" tabindex="-1"><a class="header-anchor" href="#thanks-to-our-contributors" aria-hidden="true">#</a> Thanks to our contributors!</h2>
<a href="https://github.com/{github}/graphs/contributors">
  <img src="https://contrib.rocks/image?repo={github}" />
</a>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token comment"># feishu-sheet-parser</span>

<span class="token operator">&lt;</span>h1 <span class="token assign-left variable">align</span><span class="token operator">=</span><span class="token string">"center"</span> <span class="token assign-left variable">style</span><span class="token operator">=</span><span class="token string">"border-bottom: none"</span><span class="token operator">></span>
    <span class="token operator">&lt;</span>b<span class="token operator">></span>
        <span class="token operator">&lt;</span>a <span class="token assign-left variable">href</span><span class="token operator">=</span><span class="token string">"{blog}"</span><span class="token operator">></span><span class="token punctuation">{</span>name<span class="token punctuation">}</span><span class="token operator">&lt;</span>/a<span class="token operator">></span><span class="token operator">&lt;</span>br<span class="token operator">></span>
    <span class="token operator">&lt;</span>/b<span class="token operator">></span>
    ⭐️  ESG Tracker: Automated Disclosure Monitoring  ⭐️ <span class="token operator">&lt;</span>br<span class="token operator">></span>
<span class="token operator">&lt;</span>/h<span class="token operator"><span class="token file-descriptor important">1</span>></span>

<span class="token operator">&lt;</span>p <span class="token assign-left variable">align</span><span class="token operator">=</span>center<span class="token operator">></span>
<span class="token operator">&lt;</span>a <span class="token assign-left variable">href</span><span class="token operator">=</span><span class="token string">"https://goreportcard.com/report/github.com/{github}"</span><span class="token operator">></span><span class="token operator">&lt;</span>img <span class="token assign-left variable">src</span><span class="token operator">=</span><span class="token string">"https://goreportcard.com/badge/github.com/{github}"</span> <span class="token assign-left variable">alt</span><span class="token operator">=</span><span class="token string">"A+"</span><span class="token operator">></span><span class="token operator">&lt;</span>/a<span class="token operator">></span>
<span class="token operator">&lt;</span>a <span class="token assign-left variable">href</span><span class="token operator">=</span><span class="token string">"&lt;https://github.com/issues?q=org%3A{organization}+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee>"</span><span class="token operator">></span><span class="token operator">&lt;</span>img <span class="token assign-left variable">src</span><span class="token operator">=</span><span class="token string">"&lt;https://img.shields.io/github/issues/{github}/good%20first%20issue?logo=%22github%22>"</span> <span class="token assign-left variable">alt</span><span class="token operator">=</span><span class="token string">"good first"</span><span class="token operator">></span><span class="token operator">&lt;</span>/a<span class="token operator">></span>
<span class="token operator">&lt;</span>a <span class="token assign-left variable">href</span><span class="token operator">=</span><span class="token string">"https://github.com/{github}>"</span><span class="token operator">></span><span class="token operator">&lt;</span>img <span class="token assign-left variable">src</span><span class="token operator">=</span><span class="token string">"&lt;https://img.shields.io/github/stars/{github}.svg?style=flat&amp;logo=github&amp;colorB=deeppink&amp;label=stars"</span><span class="token operator">></span><span class="token operator">&lt;</span>/a<span class="token operator">></span>
<span class="token operator">&lt;</span>a <span class="token assign-left variable">href</span><span class="token operator">=</span><span class="token string">"{slack}"</span><span class="token operator">></span><span class="token operator">&lt;</span>img <span class="token assign-left variable">src</span><span class="token operator">=</span><span class="token string">"&lt;https://img.shields.io/badge/Slack-100%2B-blueviolet?logo=slack&amp;amp;logoColor=white"</span><span class="token operator">></span><span class="token operator">&lt;</span>/a<span class="token operator">></span>
<span class="token operator">&lt;</span>a <span class="token assign-left variable">href</span><span class="token operator">=</span><span class="token string">"https://github.com/{github}/blob/main/LICENSE"</span><span class="token operator">></span><span class="token operator">&lt;</span>img <span class="token assign-left variable">src</span><span class="token operator">=</span><span class="token string">"&lt;https://img.shields.io/badge/license-Apache--2.0-green"</span><span class="token operator">></span><span class="token operator">&lt;</span>/a<span class="token operator">></span>
<span class="token operator">&lt;</span>a <span class="token assign-left variable">href</span><span class="token operator">=</span><span class="token string">"https://golang.org/"</span><span class="token operator">></span><span class="token operator">&lt;</span>img <span class="token assign-left variable">src</span><span class="token operator">=</span><span class="token string">"https://img.shields.io/badge/Language-Go-blue.svg"</span><span class="token operator">></span><span class="token operator">&lt;</span>/a<span class="token operator">></span>
<span class="token operator">&lt;</span>/p<span class="token operator">></span>

<span class="token operator">&lt;</span>/p<span class="token operator">></span>

<span class="token operator">&lt;</span>p <span class="token assign-left variable">align</span><span class="token operator">=</span><span class="token string">"center"</span><span class="token operator">></span>
    <span class="token operator">&lt;</span>a <span class="token assign-left variable">href</span><span class="token operator">=</span><span class="token string">"./README.md"</span><span class="token operator">></span><span class="token operator">&lt;</span>b<span class="token operator">></span>English<span class="token operator">&lt;</span>/b<span class="token operator">></span><span class="token operator">&lt;</span>/a<span class="token operator">></span> •
    <span class="token operator">&lt;</span>a <span class="token assign-left variable">href</span><span class="token operator">=</span><span class="token string">"./README_zh.md"</span><span class="token operator">></span><span class="token operator">&lt;</span>b<span class="token operator">></span>中文<span class="token operator">&lt;</span>/b<span class="token operator">></span><span class="token operator">&lt;</span>/a<span class="token operator">></span>
<span class="token operator">&lt;</span>/p<span class="token operator">></span>

<span class="token operator">&lt;</span>/p<span class="token operator">></span>

<span class="token comment">## Awesome features</span>

A system that monitors and tracks ESG <span class="token punctuation">(</span>Environmental, Social and Governance<span class="token punctuation">)</span> disclosures and ratings from various public data sources. It collects ESG data points from sources like Feishu spreadsheets and makes them available through an administrative interface.

<span class="token comment">## Quickstart</span>

<span class="token operator">></span> **Note**: You can get started quickly with <span class="token punctuation">{</span>name<span class="token punctuation">}</span>.



<span class="token comment">## Contributing &amp; Development</span>

<span class="token punctuation">{</span>organization<span class="token punctuation">}</span> Our goal is to build a top-level <span class="token function">open</span> <span class="token builtin class-name">source</span> community. We have a <span class="token builtin class-name">set</span> of standards, <span class="token keyword">in</span> the <span class="token punctuation">[</span>Community repository<span class="token punctuation">]</span><span class="token punctuation">(</span>https://github.com/<span class="token punctuation">{</span>organization<span class="token punctuation">}</span>/community<span class="token punctuation">)</span>.

If you'd like to contribute to this <span class="token punctuation">{</span>name<span class="token punctuation">}</span> repository, please <span class="token builtin class-name">read</span> our <span class="token punctuation">[</span>contributor documentation<span class="token punctuation">]</span><span class="token punctuation">(</span>https://github.com/<span class="token punctuation">{</span>github<span class="token punctuation">}</span>/blob/main/CONTRIBUTING.md<span class="token punctuation">)</span>.



<span class="token comment">## community meeting</span>

We welcome everyone to <span class="token function">join</span> us and contribute to <span class="token punctuation">{</span>name<span class="token punctuation">}</span>, whether you are new to <span class="token function">open</span> <span class="token builtin class-name">source</span> or professional. We are committed to promoting an <span class="token function">open</span> <span class="token builtin class-name">source</span> culture, so we offer community members neighborhood prizes and reward money <span class="token keyword">in</span> recognition of their contributions. We believe that by working together, we can build a strong community and <span class="token function">make</span> valuable <span class="token function">open</span> <span class="token builtin class-name">source</span> tools and resources available to <span class="token function">more</span> people. So <span class="token keyword">if</span> you are interested <span class="token keyword">in</span> <span class="token punctuation">{</span>name<span class="token punctuation">}</span>, please <span class="token function">join</span> our community and start contributing your ideas and skills<span class="token operator">!</span>

We take notes of each <span class="token punctuation">[</span>biweekly meeting<span class="token punctuation">]</span><span class="token punctuation">(</span>https://github.com/<span class="token punctuation">{</span>github<span class="token punctuation">}</span>/issues/381<span class="token punctuation">)</span> <span class="token keyword">in</span> <span class="token punctuation">[</span>GitHub discussions<span class="token punctuation">]</span><span class="token punctuation">(</span>https://github.com/<span class="token punctuation">{</span>github<span class="token punctuation">}</span>/discussions/categories/meeting<span class="token punctuation">)</span>, and our minutes are written <span class="token keyword">in</span> <span class="token punctuation">[</span>Google Docs<span class="token punctuation">]</span><span class="token punctuation">(</span>https://docs.google.com/document/d/1nx8MDpuG74NASx081JcCpxPgDITNTpIIos0DS6Vr9GU/edit?usp<span class="token operator">=</span>sharing<span class="token punctuation">)</span>.

<span class="token punctuation">{</span>name<span class="token punctuation">}</span> maintains a <span class="token punctuation">[</span>public roadmap<span class="token punctuation">]</span><span class="token punctuation">(</span>https://github.com/<span class="token punctuation">{</span>organization<span class="token punctuation">}</span>/community/tree/main/roadmaps<span class="token punctuation">)</span>. It gives a a high-level view of the main priorities <span class="token keyword">for</span> the project, the maturity of different features and projects, and how to influence the project direction.



<span class="token comment">## License</span>

Sealer is licensed under the Apache License, Version <span class="token number">2.0</span>. See <span class="token punctuation">[</span>LICENSE<span class="token punctuation">]</span><span class="token punctuation">(</span>https://github.com/<span class="token punctuation">{</span>github<span class="token punctuation">}</span>/tree/main/LICENSE<span class="token punctuation">)</span> <span class="token keyword">for</span> the full license text.

<span class="token punctuation">[</span><span class="token operator">!</span><span class="token punctuation">[</span>FOSSA Status<span class="token punctuation">]</span><span class="token punctuation">(</span>https://app.fossa.com/api/projects/git%2Bgithub.com%2Fsealerio%2Fsealer.svg?type<span class="token operator">=</span>large<span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">(</span>https://app.fossa.com/projects/git%2Bgithub.com%2F<span class="token punctuation">{</span>organization<span class="token punctuation">}</span>%2F<span class="token punctuation">{</span>name<span class="token punctuation">}</span>?ref<span class="token operator">=</span>badge_large<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="end-链接" tabindex="-1"><a class="header-anchor" href="#end-链接" aria-hidden="true">#</a> END 链接</h2>
<ul><li><div><a href = '62.md' style='float:left'>⬆️上一节🔗  </a><a href = '64.md' style='float: right'>  ️下一节🔗</a></div></li></ul>
<ul>
<li>
<p><RouterLink to="/">Ⓜ️回到目录🏠</RouterLink></p>
</li>
<li>
<p><a href="https://nsddd.top/archives/contributors" target="_blank" rel="noopener noreferrer"><strong>🫵参与贡献💞❤️‍🔥💖</strong><ExternalLinkIcon/></a>)</p>
</li>
<li>
<p>✴️版权声明 © ：本书所有内容遵循<a href="http://zh.wikipedia.org/wiki/Wikipedia:CC-by-sa-3.0%E5%8D%8F%E8%AE%AE%E6%96%87%E6%9C%AC" target="_blank" rel="noopener noreferrer">CC-BY-SA 3.0协议（署名-相同方式共享）©<ExternalLinkIcon/></a></p>
</li>
</ul>
</div></template>


